openapi: 3.1.0
info:
  title: Curator
  version: "1.0"
servers:
  - url: dev-api.flipp.com/curator
    description: Personalization service
paths:
  /v1/messages/{message_id}:
    patch:
      tags:
        - Content
      summary: Get Content
      description: ./docs/get_content.md
      operationId: CuratorService_GetContent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tests.openapiv3annotations.message.v1.UserInfoRequest'
        required: true
      responses:
        default:
          description: Default response can also be set
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SomeOtherResponse'
        "200":
          description: User defined operations take precedence over Google Status messages
        "201":
          description: Complex rsponse with reference and examples
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentResponse'
              example: {"publications": [{"globalId": "01HWX8FNE2ZAV0B4P5RQ7TN95G", "merchantId": 1, "dates": {"availableFrom": "2024-04-08T18:47:43Z", "availableTo": "2026-04-18T18:47:43Z", "validFrom": "2024-04-08T18:47:43Z", "validTo": "2026-04-18T18:47:43Z"}, "details": {"name": "some-name", "description": "some-description", "imageUrl": "https://example.com", "additionalInfo": {"key": "NewValue"}, "backgroundImageUrl": "https://example.com/background_image.jpg", "backgroundColor": "#FFFFFF", "tintColor": "#FFFFFF", "additionalMedia": []}, "language": "LANGUAGE_EN", "source": "", "legacyIds": null}, {"globalId": "01HXYF6J1PHEQJ9Y293NTTPH0G", "merchantId": 111111, "dates": {"availableFrom": "2024-12-01T12:00:00Z", "availableTo": "2024-12-31T12:00:00Z", "validFrom": "2024-12-01T12:00:00Z", "validTo": "2024-12-31T12:00:00Z"}, "details": {"name": "some-name", "description": "some-description", "imageUrl": "http://some-image.com", "additionalInfo": {}, "backgroundImageUrl": "https://example.com/background_image.jpg", "backgroundColor": "", "tintColor": "", "additionalMedia": []}, "language": "LANGUAGE_EN", "source": "", "legacyIds": null}], "total": 0}
        "404":
          description: Multiple response and 404
      security:
        - BasicAuth: []
components:
  schemas:
    tests.openapiv3annotations.message.v1.Address:
      type: object
      properties:
        street:
          type: string
          title: street
        city:
          type: string
          title: city
        state:
          type: string
          title: state
        zip:
          type: string
          title: zip
      title: Address
      additionalProperties: false
    tests.openapiv3annotations.message.v1.Phone:
      type: object
      properties:
        number:
          type: string
          title: number
        type:
          type: string
          title: type
      title: Phone
      additionalProperties: false
    tests.openapiv3annotations.message.v1.UserInfoRequest:
      type: object
      properties:
        id:
          type:
            - integer
            - string
          title: id
          format: int64
        label:
          type: string
          title: this is an overriden field schema title
          maxLength: 255
          description: Field level annotations
      title: This is the Request message
      additionalProperties: false
    tests.openapiv3annotations.message.v1.UserInfoResponse:
      type: object
      oneOf:
        - properties:
            address:
              title: address
              $ref: '#/components/schemas/tests.openapiv3annotations.message.v1.Address'
          title: address
          required:
            - address
        - properties:
            phone:
              title: phone
              $ref: '#/components/schemas/tests.openapiv3annotations.message.v1.Phone'
          title: phone
          required:
            - phone
      properties:
        id:
          type:
            - integer
            - string
          title: id
          format: int64
        name:
          type: string
          title: name
        email:
          type: string
          title: email
      title: This is the Response Message
      additionalProperties: false
    connect-protocol-version:
      type: number
      title: Connect-Protocol-Version
      enum:
        - 1
      description: Define the version of the Connect protocol
      const: 1
    connect-timeout-header:
      type: number
      title: Connect-Timeout-Ms
      description: Define the timeout, in ms
    connect.error:
      type: object
      properties:
        code:
          type: string
          examples:
            - not_found
          enum:
            - canceled
            - unknown
            - invalid_argument
            - deadline_exceeded
            - not_found
            - already_exists
            - permission_denied
            - resource_exhausted
            - failed_precondition
            - aborted
            - out_of_range
            - unimplemented
            - internal
            - unavailable
            - data_loss
            - unauthenticated
          description: The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
        detail:
          $ref: '#/components/schemas/google.protobuf.Any'
      title: Connect Error
      additionalProperties: true
      description: 'Error type returned by Connect: https://connectrpc.com/docs/go/errors/#http-representation'
    google.protobuf.Any:
      type: object
      properties:
        type:
          type: string
        value:
          type: string
          format: binary
        debug:
          type: object
          additionalProperties: true
      additionalProperties: true
      description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
security:
  - ApiKeyAuth: []
tags:
  - name: tests.openapiv3annotations.message.v1.Messaging1
